{"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2018-11499", "ASSIGNER": "cve@mitre.org"}, "affects": {"vendor": {"vendor_data": [{"vendor_name": "sass-lang", "product": {"product_data": [{"product_name": "libsass", "version": {"version_data": [{"version_value": "3.4.0", "version_affected": "="}, {"version_value": "3.4.1", "version_affected": "="}, {"version_value": "3.4.2", "version_affected": "="}, {"version_value": "3.4.3", "version_affected": "="}, {"version_value": "3.4.4", "version_affected": "="}, {"version_value": "3.4.5", "version_affected": "="}, {"version_value": "3.4.6", "version_affected": "="}, {"version_value": "3.4.7", "version_affected": "="}, {"version_value": "3.4.8", "version_affected": "="}, {"version_value": "3.4.9", "version_affected": "="}, {"version_value": "3.5.0", "version_affected": "="}, {"version_value": "3.5.1", "version_affected": "="}, {"version_value": "3.5.2", "version_affected": "="}, {"version_value": "3.5.3", "version_affected": "="}, {"version_value": "3.5.4", "version_affected": "="}]}}]}}]}}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-416"}]}]}, "references": {"reference_data": [{"url": "https://github.com/sass/libsass/issues/2643", "name": "https://github.com/sass/libsass/issues/2643", "refsource": "MISC", "tags": ["Issue Tracking", "Third Party Advisory"]}]}, "description": {"description_data": [{"lang": "en", "value": "A use-after-free vulnerability exists in handle_error() in sass_context.cpp in LibSass 3.4.x and 3.5.x through 3.5.4 that could be leveraged to cause a denial of service (application crash) or possibly unspecified other impact."}]}}
