{"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2018-3711", "ASSIGNER": "cve@mitre.org"}, "affects": {"vendor": {"vendor_data": []}}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-19"}]}]}, "references": {"reference_data": [{"url": "https://github.com/fastify/fastify/pull/627", "name": "https://github.com/fastify/fastify/pull/627", "refsource": "MISC", "tags": ["Exploit", "Issue Tracking", "Third Party Advisory"]}, {"url": "https://hackerone.com/reports/303632", "name": "https://hackerone.com/reports/303632", "refsource": "MISC", "tags": ["Exploit", "Issue Tracking", "Third Party Advisory"]}]}, "description": {"description_data": [{"lang": "en", "value": "Fastify node module before 0.38.0 is vulnerable to a denial-of-service attack by sending a request with 'Content-Type: application/json' and a very large payload."}]}}
