{"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2018-14611", "ASSIGNER": "cve@mitre.org"}, "affects": {"vendor": {"vendor_data": [{"vendor_name": "linux", "product": {"product_data": [{"product_name": "linux_kernel", "version": {"version_data": [{"version_value": "4.17.10", "version_affected": "<="}]}}]}}]}}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-416"}]}]}, "references": {"reference_data": [{"url": "http://www.securityfocus.com/bid/104917", "name": "104917", "refsource": "BID", "tags": ["Third Party Advisory", "VDB Entry"]}, {"url": "https://bugzilla.kernel.org/show_bug.cgi?id=199839", "name": "https://bugzilla.kernel.org/show_bug.cgi?id=199839", "refsource": "MISC", "tags": ["Exploit", "Issue Tracking", "Third Party Advisory"]}, {"url": "https://patchwork.kernel.org/patch/10503099/", "name": "https://patchwork.kernel.org/patch/10503099/", "refsource": "MISC", "tags": ["Patch", "Third Party Advisory"]}]}, "description": {"description_data": [{"lang": "en", "value": "An issue was discovered in the Linux kernel through 4.17.10. There is a use-after-free in try_merge_free_space() when mounting a crafted btrfs image, because of a lack of chunk type flag checks in btrfs_check_chunk_valid in fs/btrfs/volumes.c."}]}}
