{"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2018-8971", "ASSIGNER": "cve@mitre.org"}, "affects": {"vendor": {"vendor_data": [{"vendor_name": "gitlab", "product": {"product_data": [{"product_name": "gitlab", "version": {"version_data": [{"version_value": "10.3.8", "version_affected": "<="}]}}]}}]}}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-20"}]}]}, "references": {"reference_data": [{"url": "https://about.gitlab.com/2018/03/20/critical-security-release-gitlab-10-dot-5-dot-6-released/", "name": "https://about.gitlab.com/2018/03/20/critical-security-release-gitlab-10-dot-5-dot-6-released/", "refsource": "MISC", "tags": ["Vendor Advisory"]}, {"url": "https://www.debian.org/security/2018/dsa-4206", "name": "DSA-4206", "refsource": "DEBIAN", "tags": []}]}, "description": {"description_data": [{"lang": "en", "value": "The Auth0 integration in GitLab before 10.3.9, 10.4.x before 10.4.6, and 10.5.x before 10.5.6 has an incorrect omniauth-auth0 configuration, leading to signing in unintended users."}]}}
