{"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2018-14610", "ASSIGNER": "cve@mitre.org"}, "affects": {"vendor": {"vendor_data": [{"vendor_name": "linux", "product": {"product_data": [{"product_name": "linux_kernel", "version": {"version_data": [{"version_value": "4.17.10", "version_affected": "<="}]}}]}}]}}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-125"}, {"lang": "en", "value": "CWE-787"}]}]}, "references": {"reference_data": [{"url": "http://www.securityfocus.com/bid/104917", "name": "104917", "refsource": "BID", "tags": ["Third Party Advisory", "VDB Entry"]}, {"url": "https://bugzilla.kernel.org/show_bug.cgi?id=199837", "name": "https://bugzilla.kernel.org/show_bug.cgi?id=199837", "refsource": "MISC", "tags": ["Exploit", "Issue Tracking", "Third Party Advisory"]}, {"url": "https://patchwork.kernel.org/patch/10503415/", "name": "https://patchwork.kernel.org/patch/10503415/", "refsource": "MISC", "tags": ["Issue Tracking", "Patch", "Third Party Advisory"]}]}, "description": {"description_data": [{"lang": "en", "value": "An issue was discovered in the Linux kernel through 4.17.10. There is out-of-bounds access in write_extent_buffer() when mounting and operating a crafted btrfs image, because of a lack of verification that each block group has a corresponding chunk at mount time, within btrfs_read_block_groups in fs/btrfs/extent-tree.c."}]}}
