{"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2018-14015", "ASSIGNER": "cve@mitre.org"}, "affects": {"vendor": {"vendor_data": [{"vendor_name": "radare", "product": {"product_data": [{"product_name": "radare2", "version": {"version_data": [{"version_value": "2.7.0", "version_affected": "="}]}}]}}]}}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-119"}]}]}, "references": {"reference_data": [{"url": "https://github.com/radare/radare2/commit/bd1bab05083d80464fea854bf4b5c49aaf1b8401", "name": "https://github.com/radare/radare2/commit/bd1bab05083d80464fea854bf4b5c49aaf1b8401", "refsource": "MISC", "tags": ["Patch", "Third Party Advisory"]}, {"url": "https://github.com/radare/radare2/issues/10465", "name": "https://github.com/radare/radare2/issues/10465", "refsource": "MISC", "tags": ["Exploit", "Third Party Advisory"]}]}, "description": {"description_data": [{"lang": "en", "value": "The sdb_set_internal function in sdb.c in radare2 2.7.0 allows remote attackers to cause a denial of service (invalid read and application crash) via a crafted ELF file because of missing input validation in r_bin_dwarf_parse_comp_unit in libr/bin/dwarf.c."}]}}
