{"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2018-10920", "ASSIGNER": "cve@mitre.org"}, "affects": {"vendor": {"vendor_data": []}}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-20"}]}]}, "references": {"reference_data": [{"url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10920", "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10920", "refsource": "CONFIRM", "tags": ["Issue Tracking", "Third Party Advisory"]}, {"url": "https://www.knot-resolver.cz/2018-08-02-knot-resolver-2.4.1.html", "name": "https://www.knot-resolver.cz/2018-08-02-knot-resolver-2.4.1.html", "refsource": "CONFIRM", "tags": ["Vendor Advisory"]}]}, "description": {"description_data": [{"lang": "en", "value": "Improper input validation bug in DNS resolver component of Knot Resolver before 2.4.1 allows remote attacker to poison cache."}]}}
