{"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2018-7262", "ASSIGNER": "cve@mitre.org"}, "affects": {"vendor": {"vendor_data": [{"vendor_name": "ceph", "product": {"product_data": [{"product_name": "ceph", "version": {"version_data": [{"version_value": "13.0.0", "version_affected": "="}, {"version_value": "13.0.1", "version_affected": "="}]}}]}}, {"vendor_name": "fedoraproject", "product": {"product_data": [{"product_name": "fedora", "version": {"version_data": [{"version_value": "27", "version_affected": "="}]}}]}}]}}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-476"}]}]}, "references": {"reference_data": [{"url": "http://tracker.ceph.com/issues/23039", "name": "http://tracker.ceph.com/issues/23039", "refsource": "CONFIRM", "tags": ["Vendor Advisory"]}, {"url": "https://access.redhat.com/errata/RHSA-2018:0546", "name": "RHSA-2018:0546", "refsource": "REDHAT", "tags": ["Third Party Advisory"]}, {"url": "https://access.redhat.com/errata/RHSA-2018:0548", "name": "RHSA-2018:0548", "refsource": "REDHAT", "tags": ["Third Party Advisory"]}, {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1546611", "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1546611", "refsource": "CONFIRM", "tags": ["Issue Tracking"]}, {"url": "https://github.com/ceph/ceph/pull/20488", "name": "https://github.com/ceph/ceph/pull/20488", "refsource": "CONFIRM", "tags": ["Issue Tracking", "Third Party Advisory"]}, {"url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/74VI6EPZ6LD2O4JJXJBTYQ4U4VUO2ZDO/", "name": "FEDORA-2018-ed907ef9a0", "refsource": "FEDORA", "tags": ["Third Party Advisory"]}]}, "description": {"description_data": [{"lang": "en", "value": 'In Ceph before 12.2.3 and 13.x through 13.0.1, the rgw_civetweb.cc RGWCivetWeb::init_env function in radosgw doesn"t handle malformed HTTP headers properly, allowing for denial of service.'}]}}
