{"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2018-6552", "ASSIGNER": "cve@mitre.org"}, "affects": {"vendor": {"vendor_data": [{"vendor_name": "apport_project", "product": {"product_data": [{"product_name": "apport", "version": {"version_data": [{"version_value": "2.14.1", "version_affected": "="}, {"version_value": "2.20.1", "version_affected": "="}, {"version_value": "2.20.7", "version_affected": "="}, {"version_value": "2.20.9", "version_affected": "="}]}}]}}]}}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-399"}]}]}, "references": {"reference_data": [{"url": "https://usn.ubuntu.com/3664-2/", "name": "USN-3664-2", "refsource": "UBUNTU", "tags": ["Vendor Advisory"]}, {"url": "https://usn.ubuntu.com/usn/usn-3664-1", "name": "USN-3664-1", "refsource": "UBUNTU", "tags": ["Vendor Advisory"]}]}, "description": {"description_data": [{"lang": "en", "value": "Apport does not properly handle crashes originating from a PID namespace allowing local users to create certain files as root which an attacker could leverage to perform a denial of service via resource exhaustion, possibly gain root privileges, or escape from containers. The is_same_ns() function returns True when /proc/<global pid>/ does not exist in order to indicate that the crash should be handled in the global namespace rather than inside of a container. However, the portion of the data/apport code that decides whether or not to forward a crash to a container does not always replace sys.argv[1] with the value stored in the host_pid variable when /proc/<global pid>/ does not exist which results in the container pid being used in the global namespace. This flaw affects versions 2.20.8-0ubuntu4 through 2.20.9-0ubuntu7, 2.20.7-0ubuntu3.7, 2.20.7-0ubuntu3.8, 2.20.1-0ubuntu2.15 through 2.20.1-0ubuntu2.17, and 2.14.1-0ubuntu3.28."}]}}
