{"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2018-10870", "ASSIGNER": "cve@mitre.org"}, "affects": {"vendor": {"vendor_data": [{"vendor_name": "redhat", "product": {"product_data": [{"product_name": "certification", "version": {"version_data": [{"version_value": "-", "version_affected": "="}]}}]}}]}}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-20"}]}]}, "references": {"reference_data": [{"url": "http://www.securityfocus.com/bid/104857", "name": "104857", "refsource": "BID", "tags": ["Third Party Advisory", "VDB Entry"]}, {"url": "https://access.redhat.com/errata/RHSA-2018:2373", "name": "RHSA-2018:2373", "refsource": "REDHAT", "tags": ["Vendor Advisory"]}, {"url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10870", "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10870", "refsource": "CONFIRM", "tags": ["Issue Tracking", "Mitigation", "Vendor Advisory"]}]}, "description": {"description_data": [{"lang": "en", "value": "redhat-certification does not properly sanitize paths in rhcertStore.py:__saveResultsFile. A remote attacker could use this flaw to overwrite any file, potentially gaining remote code execution."}]}}
