{"data_type": "CVE", "data_format": "MITRE", "data_version": "4.0", "CVE_data_meta": {"ID": "CVE-2018-12605", "ASSIGNER": "cve@mitre.org"}, "affects": {"vendor": {"vendor_data": []}}, "problemtype": {"problemtype_data": [{"description": [{"lang": "en", "value": "CWE-79"}]}]}, "references": {"reference_data": [{"url": "https://about.gitlab.com/2018/06/25/security-release-gitlab-11-dot-0-dot-1-released/", "name": "https://about.gitlab.com/2018/06/25/security-release-gitlab-11-dot-0-dot-1-released/", "refsource": "CONFIRM", "tags": ["Vendor Advisory"]}, {"url": "https://gitlab.com/gitlab-org/gitlab-ce/issues/45168", "name": "https://gitlab.com/gitlab-org/gitlab-ce/issues/45168", "refsource": "CONFIRM", "tags": ["Exploit", "Issue Tracking", "Patch", "Vendor Advisory"]}]}, "description": {"description_data": [{"lang": "en", "value": 'An issue was discovered in GitLab Community Edition and Enterprise Edition 10.7.x before 10.7.6. The usage of "url_for" contained a XSS issue due to it allowing arbitrary protocols as a parameter.'}]}}
